// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: proto/task.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "task";

export interface SubmitTaskRequest {
  name: string;
  durationSeconds: number;
}

export interface SubmitTaskResponse {
  taskId: string;
}

export interface WatchTaskRequest {
  taskId: string;
}

export interface TaskUpdate {
  taskId: string;
  progress: number;
  status: string;
}

export const TASK_PACKAGE_NAME = "task";

export interface TaskServiceClient {
  submitTask(request: SubmitTaskRequest): Observable<SubmitTaskResponse>;

  watchTask(request: WatchTaskRequest): Observable<TaskUpdate>;
}

export interface TaskServiceController {
  submitTask(
    request: SubmitTaskRequest,
  ): Promise<SubmitTaskResponse> | Observable<SubmitTaskResponse> | SubmitTaskResponse;

  watchTask(request: WatchTaskRequest): Observable<TaskUpdate>;
}

export function TaskServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["submitTask", "watchTask"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TASK_SERVICE_NAME = "TaskService";
